---
# tasks file for external-port-connectivity-validator-server
- name: Client validator with proxy
  debug:
    msg: 'Source Server: {{ local_address }}'

- name: Validate for open port {{ target_server }}:{{ check_port }} with proxy
  uri:
    url: 'http://{{ target_server }}:{{ check_port }}/check'
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
