---
# tasks file for external-port-connectivity-validator-server
- name: Source server to connect from
  debug:
    msg: 'Source Server: {{ local_address }}'

- name: Validate for open port {{ target_server }}:{{ check_port }}
  uri:
    url: 'http://{{ target_server }}:{{ check_port }}/check'

- name: Shutdown validation server {{ target_server }}:{{ check_port }}
  uri:
    url: 'http://{{ target_server }}:{{ check_port }}/done'
  register: done
  failed_when: not done.failed
